### ISSUE TITLE
Broken Build since few months

### ISSUE THREAD

**Issue by ind3p3nd3nt** [Sysinternals/ProcDump-for-Linux#101]
### Expected behavior
build success
### Actual behavior
molly@sickvpn:~/ProcDump-for-Linux$ make
rm -rf obj
rm -rf bin
rm -rf /home/molly/ProcDump-for-Linux/pkgbuild
gcc -c -g -o obj/CoreDumpWriter.o src/CoreDumpWriter.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Events.o src/Events.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Handle.o src/Handle.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Logging.o src/Logging.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Procdump.o src/Procdump.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/ProcDumpConfiguration.o src/ProcDumpConfiguration.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Process.o src/Process.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/TriggerThreadProcs.o src/TriggerThreadProcs.c -Wall -I ./include -pthread -std=gnu99
gcc -o bin/procdump obj/CoreDumpWriter.o obj/Events.o obj/Handle.o obj/Logging.o obj/Procdump.o obj/ProcDumpConfiguration.o obj/Process.o obj/TriggerThreadProcs.o -Wall -I ./include -pthread -std=gnu99
/usr/bin/ld: obj/Events.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Handle.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Logging.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Logging.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: multiple definition of `g_config'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: first defined here
/usr/bin/ld: obj/Logging.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: multiple definition of `HZ'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: first defined here
/usr/bin/ld: obj/Logging.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: first defined here
/usr/bin/ld: obj/Procdump.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/Procdump.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: multiple definition of `g_config'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: first defined here
/usr/bin/ld: obj/Procdump.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: multiple definition of `HZ'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: first defined here
/usr/bin/ld: obj/Procdump.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: multiple definition of `g_config'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: multiple definition of `HZ'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: first defined here
/usr/bin/ld: obj/ProcDumpConfiguration.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: first defined here
/usr/bin/ld: obj/Process.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: multiple definition of `LoggerLock'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/Logging.h:42: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: multiple definition of `g_config'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:43: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: multiple definition of `HZ'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:45: first defined here
/usr/bin/ld: obj/TriggerThreadProcs.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: multiple definition of `MAXIMUM_CPU'; obj/CoreDumpWriter.o:/home/molly/ProcDump-for-Linux/./include/ProcDumpConfiguration.h:46: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:57: bin/procdump] Error 1

### Steps to reproduce the behavior
1. clone
2. make
3. see error

### System information (e.g., distro, kernel version, etc.)
github.com/ind3p3nd3nt/MollyEskam-Linux (custom Kali ISO with KDE, full-upgrade system) amd64
Linux sickvpn 5.8.0-kali2-amd64 #1 SMP Debian 5.8.10-1kali1 (2020-09-22) x86_64 GNU/Linux

**Comment by gaowayne** [comment]
what is status for this issue? any fix so far?
this tool can catch hang dump for C++/C application, right? it is not for .net core only?

**Comment by jahabibi** [comment]
Procdump for Linux can take core dumps for C & C++ applications. It is not limited to .Net Core. 

This issue is resolved with #104.
