### ISSUE TITLE
Optimize TUI with latest notcurses

### ISSUE THREAD

**Issue by WSLUser** [Sysinternals/ProcDump-for-Linux#119]
### Expected behavior
I expect the best visual representations possible for this utility.
### Actual behavior
Could be improved through use of notcurses.

I would love to see this optimized for use with the notcurses library to bring better graphics input/output to terminals. https://github.com/dankamongmen/notcurses/releases Example usage: https://github.com/dankamongmen/growlight

### System information (e.g., distro, kernel version, etc.)
All

**Comment by MarioHewardt** [comment]
Are there particular Ux scenarios that you feel should be improved? If so, it would be helpful to understand what those are.

**Comment by WSLUser** [comment]
Mostly, I'd like to see less dependency on ncurses as I'd prefer something similar looking to the project I linked to as example, which does similar thing to this tool.

**Comment by WSLUser** [comment]
Green: Info. Yellow: Warning, Red: Error. VS and other projects with debugging have this color support and more depending on other extras it shows.

**Comment by WSLUser** [comment]
I'd seriously take a look at the official demo of notcurses and maybe you could get some ideas on where UX can be improved besides what I've listed here.

**Comment by jahabibi** [comment]
At this point in time this issue is out of scope due to the fact that Procdump does not have a TUI.

**Comment by WSLUser** [comment]
There is a command-line mode now that would likely still help make things appear better. See https://github.com/dankamongmen/notcurses/issues/785 and https://github.com/dankamongmen/notcurses/blob/master/USAGE.md

**Comment by WSLUser** [comment]
Should I create a new issue regarding the CLI-mode or can we re-open this one?
