### ISSUE TITLE
CreateTriggerThreads function maybe has array overflow

### ISSUE THREAD

**Issue by evazhuang** [Sysinternals/ProcDump-for-Linux#128]
The variable “pthread_t Threads[MAX_TRIGGERS]” of struct ProcDumpConfiguration is maybe overflow。
The value of MAX_TRIGGERS is 3. But the function CreateTriggerThreads can create over 3 threads. 
When I use cmd "procdump -C 10 -M 2 -F 10 -T 2 -p 27797 -d", it can not generat the core dump.

**Comment by MarioHewardt** [comment]
Fixed.
