### ISSUE TITLE
Failed to create dump

### ISSUE THREAD

**Issue by mathewhoopertr** [Sysinternals/ProcDump-for-Linux#134]
### Expected behavior
Dump file to be created!

### Actual behavior
Getting the following error message:

An error occurred while generating the core dump for .NET 3.x+ process
### Steps to reproduce the behavior
1. Run the following command as root - procdump -w dotnet -d
2. Review the output from syslog
3. Getting the following log output

Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - INFO]: Found process with PID 3747
Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - DEBUG]: TimerThread: Starting Trigger Thread in src/TriggerThreadProcs.c, at line 291
Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - INFO]: Timed:
Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - DEBUG]: CoreCLR diagnostics socket: #020#022 in src/CoreDumpWriter.c, at line 140
Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - DEBUG]: Failed to connect to socket for .NET Core dump generation. in src/CoreDumpWriter.c, at line 287
Feb 21 17:04:48 ProcDump[10035]: [17:04:48 - ERROR]: An error occurred while generating the core dump for .NET 3.x+ process
Feb 21 17:04:50 ProcDump[10035]: [17:04:50 - INFO]: Quit
Feb 21 17:04:50 ProcDump[10035]: [17:04:50 - DEBUG]: TimerThread: Exiting Trigger Thread in src/TriggerThreadProcs.c, at line 312

So with my _very_ limited knowledge of c++, it looks like it successfully creates the diagnostics socket but fails to connect  

### System information (e.g., distro, kernel version, etc.)
Amazon Linux 2

To install the package, I used yum localinstall filenameof.rpm where it installed the dependency for it.

**Comment by MarioHewardt** [comment]
Thanks for reporting this. Can you try explicitly targeting the target process using the PID? You can use a plethora of ways to find the PID such as ps.

**Comment by mathewhoopertr** [comment]
Hey @MarioHewardt 

I probably should have added that I tried that with the same result - I assumed it did the same thing with the exception of finding the process ID.  The target version of .net is 3.1.

Thanks

**Comment by MarioHewardt** [comment]
Looping back to this, sorry for the delay. 

How are you executing your dotnet app? Is it via 'dotnet run'? I believe there can be multiple instances of the dotnet process if executed via dotnet and only the main app will have the diagnostics socket open. Do you see multiple dotnet processes running when you are able to reproduce the problem (do a ps -a and look for dotnet processes or your target app process name)?

**Comment by MarioHewardt** [comment]
Closing for now. If you are still seeing the issue, please feel free to reopen.
