### ISSUE TITLE
Generate a dump when a .NET gen collection starts and ends

### ISSUE THREAD

**Issue by MarioHewardt** [Sysinternals/ProcDump-for-Linux#188]
New switch: -gcgen <gen>

**Comment by ozkanpakdil-redgate** [comment]
@MarioHewardt gcgen parameter does not exist on doc for windows https://learn.microsoft.com/en-us/sysinternals/downloads/procdump 

Is there a way to get this for windows ?

**Comment by MarioHewardt** [comment]
Hi - gcgen is not exposed in the Windows version. We'll add a backlog item for future consideration.

**Comment by ozkanpakdil-redgate** [comment]
In case anyone find themselves here, here is a way to run GC on second process https://github.com/ozkanpakdil/dotnet-examples/tree/main/GCDumper
