### ISSUE TITLE
procdump support on mac os

### ISSUE THREAD

**Issue by lycfr** [Sysinternals/ProcDump-for-Linux#222]
### Steps to reproduce the behavior
1. 
2.
3.

**Comment by MarioHewardt** [comment]
Hi - thanks for the feedback. While we don't have any current plans on adding mac os support, I've tagged this issue with the enhancement tags so we can track it.

**Comment by MarioHewardt** [comment]
Hi - Support for Mac has now been implemented - https://github.com/microsoft/ProcDump-for-Mac
