### ISSUE TITLE
What is the default dump type and how to get a full dump file?

### ISSUE THREAD

**Issue by satvu** [Sysinternals/ProcDump-for-Linux#253]
Is there an equivalent for specifying dump type like the [windows version](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump#using-procdump)? If not, what is the default and is it possible to get a full dump file?

**Comment by MarioHewardt** [comment]
Hi - by default ProcDump uses coredump_filter which specifies what should be included in the dump that is generated. You can change that by using the -mc switch. Please see man core for the available bit params. 

           bit 0  Dump anonymous private mappings.
           bit 1  Dump anonymous shared mappings.
           bit 2  Dump file-backed private mappings.
           bit 3  Dump file-backed shared mappings.
           bit 4 (since Linux 2.6.24)
                  Dump ELF headers.
           bit 5 (since Linux 2.6.28)
                  Dump private huge pages.
           bit 6 (since Linux 2.6.28)
                  Dump shared huge pages.
           bit 7 (since Linux 4.4)
                  Dump private DAX pages.
           bit 8 (since Linux 4.4)
                  Dump shared DAX pages.

**Comment by satvu** [comment]
Thanks - closing as answered.
