### ISSUE TITLE
Request for a feature (core-dump on a specific return signal).

### ISSUE THREAD

**Issue by JohnTroony** [Sysinternals/ProcDump-for-Linux#48]
Installed the Ubuntu x64 deb on a Debian instance [`4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux`] and everything seems to work fine. Is it possible to have an option to create a core dump depending on a return signal ? e.g. SIGBUS, SIGSEGV, SIGTRAP e.t.c

**Comment by josalem** [comment]
I like this idea a lot, and it's something we've discussed before, but if I'm not mistaken, we would need to be tracing the program explicitly via `ptrace` or similar to intercept signals.  This will incur an overhead.  Linux already has faculties for creating core dumps for certain signals (see: [signal disposition](http://man7.org/linux/man-pages/man7/signal.7.html)).  Can you expand on what the use case would be for having procdump intercept signals, other than to extend the feature set of the tool?

**Comment by blattersturm** [comment]
On Windows, doesn't `procdump -e` already attach to the process as a debugger in a similar fashion?

We're shipping a server application, and to collect (more detailed) crash reports, we actually rely on users reproducing said issue and running `procdump -e` on Windows, and having an equivalent tool for Linux would be fairly helpful, leading to a similar workflow for end users.

**Comment by JohnTroony** [comment]
@josalem I do some fuzzing on Linux and most of the time I want to get literally all kind of feedback from the applications under test, even if they don't crash. Well, I think you are right with the overhead in including such a feature. Thanks for the pointers, will definitely check out the shared resources. Currently I use Python `import os.system` and check for the return signal for each input used. However, I realized this is not effective since I use a block of  `if` statements to determine the next action e.g. if a SIGPIPE is caught before a SIGABRT, I will only analyze the application in the context of SIGPIPE unless I repeat the test with the used input and watch for the other signals. The repetitions is where I think ProcDump could assist - watching for a particular signal and dumping the process :)

**Comment by josalem** [comment]
I can certainly see the value in that, and it does seem like something that could only be done from within the process (pretty much useless) or using `ptrace`.  If the perf penalty of a true trace of the other process is an acceptable price to pay, I don't see why we couldn't incorporate this feature.  We are in the initial planning phases of the next set of features for procdump, so we will keep this in mind as we plan.  For now I'll put it in the future milestone for tracking and leave the issue open.  If this ends up being developed, we can tag it back to this issue.

**Comment by JohnTroony** [comment]
Cool. Thanks :+1:

**Comment by jahabibi** [comment]
As of [Procdump 1.2](https://github.com/Sysinternals/ProcDump-for-Linux/releases/tag/1.2) we now support the ability to create memory dumps on process signals with the `-G` flag.
