### ISSUE TITLE
Support ARM32 

### ISSUE THREAD

**Issue by philipktlin** [Sysinternals/ProcDump-for-Linux#54]
I would like to ask, is there any plan to support ARM version ProcDump on Raspbian OS?  And what alternative command can I use to gather .Net memory dump inside a docker container?

**Comment by philipktlin** [comment]
Just a friendly ping.

**Comment by MarioHewardt** [comment]
There are currently no short term plans but we will keep it on the backlog.

**Comment by olaf-lange** [comment]
I'd like to second this request. ;-) Please give us ARM binaries.

**Comment by MagicAndre1981** [comment]
> There are currently no short term plans but we will keep it on the backlog.

any update on this? I would also like to try it on my Pi4

**Comment by MarioHewardt** [comment]
Apologies for the very, very late response. 

I have successfully built ProcDump on Ubuntu 20.04 on my raspberry pi 4 and it works as expected. I also tried cross compilation on x64 Ubuntu targeting ARM64 which also works as expected. If there is enough interest (please let me know) we will consider publishing ARM packages.

**Comment by MagicAndre1981** [comment]
yes, please release Linux arm(64) builds for Raspi OS

**Comment by MarioHewardt** [comment]
Closing this issue for now since ProcDump can be compiled and runs on ARM. We will consider creating ARM packages and will file a new issue once the decision has been made. If you encounter any problems with compiling and running ProcDump on ARM please file a new issue and we'll take a look.

**Comment by MagicAndre1981** [comment]
> Closing this issue for now since ProcDump can be compiled and runs on ARM. 

what are the commands to compile ProcDump for ARM(64) to run it on RaspiOS?
