### ISSUE TITLE
CPU threshold trigger doesn't work

### ISSUE THREAD

**Issue by inoue-katsumi** [Sysinternals/ProcDump-for-Linux#76]
### Expected behavior
1. With "-C 2“  for example, procdump is only triggered when particular process is using
more than 2% of CPU.
2. With "-c 2" for example, procdump is only triggered when particular process is using less than 2% of CPU.

### Actual behavior
1. "-C 2" and particular process(mysqld) started using 99% of CPU. procdump didn't dump.
2. "-c 2" and mysqld using 99% of CPU.  Procdump dumped and created core file.

### Steps to reproduce the behavior
1. sudo procdump -C 2 -n 2 -s 3 -p $(pgrep -f mysqld) &
2.  Connect to mysql using SQL tool
3.  select count(*) from large_table a, large_table b, large_table c, large_table d
4. run 'top' or 'ps' and confirm that mysqld process is using 99% CPU
5. Wait 20 seconds. Core dump file won't be created.

### System information (e.g., distro, kernel version, etc.)
CentOS 7.7
kvm vm
mysqld running in docker

**Comment by inoue-katsumi** [comment]
"procdump -C 65" worked for a 'cat' process which I started in the same docker instance with command below.

$  docker exec -it wordpress_mysql_1 bash -c 'cat /dev/urandom > /dev/null'

**Comment by inoue-katsumi** [comment]
mysql was run as non-root user . But I guess this doesn't matter.

**Comment by MarioHewardt** [comment]
Thanks for bringing this up. In the 99% MySQL scenario, can you try dumping using gcore and let us know if that generates a dump?

**Comment by MarioHewardt** [comment]
@inoue-katsumi Did you get this resolved? If not, did you try just using gcore?
