### ISSUE TITLE
Making the Linux and Windows version more compatible to each other

### ISSUE THREAD

**Issue by theuserbl** [Sysinternals/ProcDump-for-Linux#86]
Have looked at the different options of the Linux ProcDump with the Windows documentation at
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

It isn't the problem, that one ProcDump have additional options then the other. But they have same option names with different funtions.

-m, -n and -s have same functions.
But -h, -c, -d, -p and -w have different functions.

`-?` (only for Windows)
exists only on Window. Seems to be the same as on Linux the `-h`
Windows: "Use -? -e to see example command lines."

`-h` (different)
Linux:  "Prints this help screen"
Windows: "Write dump if process has a hung window (does not respond to window messages for at least 5 seconds)."

`-c` (different)
Linux: "Trigger core dump generation when CPU is less than specified value (0 to 100 * nCPU)"
Windows: "CPU threshold at which to create a dump of the process."

`-m` (same)
Linux: "Trigger core dump generation when when memory commit is less than specified value (MB)"
Windows: "Memory commit threshold in MB at which to create a dump."

`-n` (same)
Linux: "Number of core dumps to write before exiting (default is 1)"
Windows: "Number of dumps to write before exiting."

`-s` (same)
Linux: "Consecutive seconds before dump is written (default is 10)"
Windows: "Consecutive seconds before dump is written (default is 10)."

`-d` (different)
Linux: "Writes diagnostic logs to syslog"
Windows: "Invoke the minidump callback routine named MiniDumpCallbackRoutine of the specified DLL."

`-p` (different)
Linux: "pid of the process"
Windows: "Trigger on the specified performance counter when the threshold is exceeded. Note: to specify a process counter when there are multiple instances of the process running, use the process ID with the following syntax: "\Process(<name>_<pid>)\counter""

`-w` (different)
Linux:  "Name of the process executable"
Windows: "Wait for the specified process to launch if it's not running."

**Comment by MarioHewardt** [comment]
Thanks for the detailed write up on the similarities/differences. The challenge with aligning Win/Linux at this point is breaking existing usage of it.
