### ISSUE TITLE
Number of Dumps have no effect

### ISSUE THREAD

**Issue by theuserbl** [Sysinternals/ProcDump-for-Linux#89]
The entered number of dumbs have no effect.
Tested on Lubuntu 20.04 in VirtualBox.

I have used your example in the animated gif on the frontpage and have done it to an script:

```
#!/bin/bash

cat /dev/urandom > /dev/null &
sudo ./procdump -p $! -C 80 -n 3 -s 3
kill $!
```

It dumps infinitely time stamps. But at the header stands "Number of Dumps:        3".

Also interesting is, that was not at the beginning. Version 1.0 and 1.0.1 working ok and stopping after 3 dumps, but version 1.1 and 1.1.1 don't stop dumping.

I have looked, after which commit the bug comes. The Commit of Dec 3, 2019 creates the problem with the infinity dumps
https://github.com/microsoft/ProcDump-for-Linux/commit/aff9caf830fb05c7746ac7df0fcb5b5bd0ff784f
It was a big commit, which added a .NET core dump generator, fixed a lot of bugs and created the mentioned bug.

**Comment by MarioHewardt** [comment]
Thanks for the thorough report. We'll investigate.

**Comment by MarioHewardt** [comment]
Sorry for the delay. I've tested this on Ubuntu 20.04 and 18.04 and it works as expected (stops after 3 dumps). I noticed you were testing on Lubuntu and it's possible there is something specific for that environment. While we like to make sure Procdump works across all distributions we currently only support the distributions listed in the install doc.
